### PR TITLE
Fix issue with calling pybind functions with one argument

### LINKED ISSUE #70: Problems with offset in MVD3
Python functions have signature `xxx(offset=0, count=0)`. Therefore a user can pass only the offset. However, from the c++ side, at least in MVD3, `count = 0` means whole range.

Furthermore, the functions getPositions (etc) which do a conversion of the data structure and dont take into account this offset, and the conversion loops may fail

### PR DESCRIPTION
**Pull request by iomaganaris**
- When pybind functions are called with one argument return the object
  in this offset
- Avoid accessing memory out of bounds when range.count == 0
- Fixes #70

### CODE REVIEW

File: python/mvdtool.cpp [hunk 1]
```diff
@@ -143,20 +143,34 @@ PYBIND11_MODULE(mvdtool, mvd) {
                 f.openComboTsv(filename);
              },
              "filename"_a)
+        .def("positions", [](const File& f, int offset) {
```
Comment (ferdonline) [inline python/mvdtool.cpp]: Isnt there a conflict with the overload below? The signature bellow also allows a single param.

File: python/mvdtool.cpp [hunk 2]
```diff
@@ -143,20 +143,34 @@ PYBIND11_MODULE(mvdtool, mvd) {
...
+                auto res = f.getPositions(Range(offset, 1));
+                return py::array({res.shape()[0], res.shape()[1]}, res.data());
+             },
+             "offset"_a)
```
Comment (ferdonline) [inline python/mvdtool.cpp]: Cant we drop this `"offset"_a` It seems not doing anything...

File: python/mvdtool.cpp (hunk 1 above)
Comment (iomaganaris) [reply python/mvdtool.cpp]: As discussed offline, pybind sets the precedence in this case based on the order that the functions where declared. I decided to specifically declare the functions for all the cases to avoid any conflict in the future

File: include/mvdtool/bits/mvd3_misc.hpp [hunk 3]
```diff
@@ -185,9 +187,10 @@ inline Rotations MVD3File::getRotations(const Range& range) const {
     HighFive::DataSet set = _hdf5_file.getDataSet(did_cells_rotations);
     if (!range.is_empty()) {
```
Comment (ferdonline) [inline include/mvdtool/bits/mvd3_misc.hpp]: My only remark is that `is_empty` now is misleading. Maybe we could drop it and have an expressive
`range == range::all()`. (Maybe all can even have a `constexpr all` object ?

**Comment by ferdonline** [comment]
Nice work. I have a small comment which I think would improve a bit the readability, but nothing serious.

File: include/mvdtool/bits/mvd3_misc.hpp (hunk 3 above)
Comment (iomaganaris) [reply include/mvdtool/bits/mvd3_misc.hpp]: I agree that the name is not representative.. Maybe simply renaming it to `is_until_end` is sufficient.
From my point of view, `is_empty` checks if ` count == 0`, meaning that even in case that the range is instantiated like `Range(offset, 0)` it should return `true`, since this would mean all the elements from `offset` until the `end`.
What do you think about that?

Comment (ferdonline) [reply include/mvdtool/bits/mvd3_misc.hpp]: right, the conditions would have to change. At the moment I find not so cool that in both il/else parts we have to compute the range.
What I have in mind is something like python slices. Apparently now that's all hidden but, anyway, check https://docs.python.org/3/c-api/slice.html#c.PySlice_AdjustIndices
So instead of checking for a particular case when `count == 0` adjust in some way, we could have a nicer OO way and if not range::all, do `count = range.adjust_indices(seq_length)`

Comment (iomaganaris) [reply include/mvdtool/bits/mvd3_misc.hpp]: That's a very good point! :+1:
I am working on it

Comment (iomaganaris) [reply include/mvdtool/bits/mvd3_misc.hpp]: I refactored this a bit. Let me know what you think :slightly_smiling_face:
